name: BossBarMessages
version: 1.0
main: me.abandoncaptian.BBMessages.Main
description: Boss Bar Messaging plugin made by abandoncaptian
commands:
  bossbar:
    aliases: [bb]
    description: Boss Bar Meessages Command